services:
  postgres:
    image: postgres:16
    container_name: moonland-db
    environment:
      POSTGRES_DB: moonland
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
